homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 26
  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

http:
  #api_password: !secret http_password
  

####### Components #######

updater:
history:
logbook:
frontend:
discovery:
recorder:
  purge_days: 4

logger:
    default: info
    logs:
     group.settings: critical


  
####### Sensors #######

sensor:
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload


  - platform: yweather
    monitored_conditions:
      - weather
      - temperature
      - humidity

####### Zones #######

####### Inputs #######

####### Groups #######
group: !include group.yaml


