homeassistant:
  name: Sockr Base
  latitude: !secret lat
  longitude: !secret long
  elevation: 26
  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  

##########################
####### Components #######
##########################

updater:
history:
logbook:
frontend:
discovery:
recorder:
  purge_days: 4

logger:
    default: info
    logs:
     group.settings: critical

light:
  light:
  platform: hue
  host: 192.168.2.68
  allow_unreachable: true
  
media_player:
  platform: cast
  host: 192.168.2.27

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.1/24
    home_interval: 5
    track_new_devices: no
  
  - platform: owntracks
    max_gps_accuracy: 200

mqtt:
  broker: 192.168.2.52
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass
 
 
#######################
####### Sensors #######
#######################

sensor:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

sensor 2:
  platform: plex
  host: 192.168.1.80
  username: !secret plex_user
  password: !secret plex_pass
  server: Flashlight
  
sensor 3:
  platform: forecast
  api_key: !secret forecast_api
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary

sensor 4:
    platform: google_travel_time
    name: Travel Time
    api_key: !secret google_api
    origin: !secret travel_origin
    destination: !secret travel_destination
    options:
      arrival_time: 08:00:00
      mode: transit

      
#####################    
####### Zones #######
#####################

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  radius: 100
  icon: mdi:home-variant

zone 2:
  name: Work
  latitude: !secret lat_work
  longitude: !secret long_work
  radius: 300
  icon: mdi:school

zone 3:
  name: WhoValley
  latitude: !secret lat_who
  longitude: !secret long_who
  radius: 100
  icon: mdi:gondola
  

######################
####### Inputs #######
######################




######################
####### Groups #######
######################

group:
  
  Info:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.plex

  Weather:
    - sensor.weather_summary
    - sensor.weather_temperature
    - sensor.weather_hourly_summary
  
  Dwellers:
    - device_tracker.192168224
    - sensor.travel_time
