homeassistant:
  name: Sockr Base
  latitude: !secret lat
  longitude: !secret long
  elevation: 26
  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  

##########################
####### Components #######
##########################

updater:
history:
logbook:
frontend:
discovery:
sun:
recorder:
  purge_days: 4

logger:
    default: info
    logs:
     group.settings: critical

light:
  light:
  platform: hue
  host: 192.168.2.68
  allow_unreachable: true
  
media_player:
  platform: cast
  host: 192.168.2.27

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.1/24
    home_interval: 5
    track_new_devices: no
    interval_seconds: 30
  
  - platform: owntracks
    max_gps_accuracy: 200

mqtt:
  broker: 192.168.2.52
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass

 
 
#######################
####### Sensors #######
#######################

sensor:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

sensor 2:
  platform: plex
  host: 192.168.1.80
  username: !secret plex_user
  password: !secret plex_pass
  server: Flashlight
  
sensor 3:
  platform: forecast
  api_key: !secret forecast_api
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary
    - wind_speed
    - wind_bearing
    - precip_type

sensor 4:
  - platform: google_travel_time
    name: Home to Work
    api_key: !secret google_api
    origin: !secret travel_origin
    destination: !secret travel_destination
    options:
      arrival_time: 08:00:00
      mode: transit
      
  - platform: google_travel_time
    name: Phone to Work
    api_key: !secret google_api
    origin: device_tracker.shjosan_oneplus2
    destination: zone.work
    
  - platform: google_travel_time
    name: Phone to WhoValley
    api_key: !secret google_api
    origin: device_tracker.shjosan_oneplus2
    destination: zone.whovalley

sensor 5:
  platform: sabnzbd
  name: SAB
  api_key: !secret sab_api
  base_url: !secret sab_url
  monitored_variables:
    - type: 'current_status'
    - type: 'queue_size'
#   - type: 'queue_remaining'
      
#####################    
####### Zones #######
#####################

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  radius: 100
  icon: mdi:home-variant

zone 2:
  name: Work
  latitude: !secret lat_work
  longitude: !secret long_work
  radius: 300
  icon: mdi:home-modern

zone 3:
  name: WhoValley
  latitude: !secret lat_who
  longitude: !secret long_who
  radius: 100
  icon: mdi:gondola
  passive: true

######################
####### Scenes #######
######################

scene:
  - name: 'Normal Mode'
    entities:
      light.vardagsrum_tak_1:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
      light.vardagsrum_tak_2:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
      light.vardagsrum_tak_3:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
      light.vardagsrum_tak_4:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
        
  - name: 'Kitchen On'
    entities:
      light.kk:
        state: on
        brightness: 254
        color_temp: 199
        rgb_color: [255,240,219]
        
  - name: 'Night Lights'
    entities:
      light.vardagsrum_tak_1:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]
      light.vardagsrum_tak_2:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]
      light.vardagsrum_tak_3:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]
      light.vardagsrum_tak_4:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]  
      light.kk:
        state: on
        brightness: 75
        color_temp: 500
        rgb_color: [51,51,205]
        
  - name: 'All Off'
    entities:
      light.vardagsrum_tak_1:
        state: off
      light.vardagsrum_tak_2:
        state: off
      light.vardagsrum_tak_3:
        state: off
      light.vardagsrum_tak_4:
        state: off
      light.kk:
        state: off
      light.sovrum:
        state: off
      

        
        
##########################
####### Automation #######
##########################

automation:
- alias: 'Coming Home'
  
  trigger:
   - platform: state
     entity_id: group.dwellers
     state: 'home'
      
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        before: '23:59'
        
  action:
    service: light.turn_on
    entity_id: group.ceiling
    data:
      brightness: 111
      rgb_color: [237,177,89]
      color_temp: 500


######################
####### Groups #######
######################

group:

  default_view:
    view: yes
    entities:
      - group.weather
      - group.info
      - group.dwellers
      
  lightsview:
    name: Lights
    view: yes
    entities:
      - group.lights
      - group.ceiling
      - group.modes
      
  media:
    name: Media
    view: yes
    entities:
      - media_player.kurvan
      - media_player.my_qv151e
      - media_player.plex_web_chrome
      - media_player.ponyo

  
  info:
    name: Info
    entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.plex
    - sensor.sab_status
    - sensor.sab_queue

  weather:
    name: Weather
    entities:
    - sun.sun
    - sensor.weather_summary
    - sensor.weather_temperature
    - sensor.weather_precip_type
    - sensor.weather_wind_speed
    - sensor.weather_wind_bearing
    - sensor.weather_hourly_summary
  
  dwellers:
    name: Dwellers corner
    entities:
    - device_tracker.shjosan_oneplus2
    - sensor.home_to_work
    - sensor.phone_to_work
    - sensor.phone_to_whovalley 

#  transit:
#    name: Transit
#    entities:
  
    
  ceiling:
    name: Ceiling
    entities:
    - light.vardagsrum_tak_1
    - light.vardagsrum_tak_2
    - light.vardagsrum_tak_3
    - light.vardagsrum_tak_4
   
  lights:
    name: Other lights
    entities:
    - light.sovrum
    - light.kk
    
  modes:
    name: Light modes
    entities:
    - scene.normal_mode
    - scene.kitchen_on
    - scene.night_lights
    - scene.all_off
