homeassistant:
  name: Sockr Base
  latitude: !secret lat
  longitude: !secret long
  elevation: 26
  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

http:
#  api_password: !secret http_password
  

##########################
####### Components #######
##########################

updater:
history:
logbook:
frontend:
discovery:
sun:
recorder:
  purge_days: 4

logger:
    default: info
    logs:
     group.settings: critical

light:
  platform: hue
  host: 192.168.2.40
  allow_unreachable: true
  
media_player:
  platform: cast
  host: 192.168.2.27

device_tracker:
  platform: nmap_tracker
  hosts: 192.168.2.5-45
  home_interval: 5
  track_new_devices: no
  interval_seconds: 30
  consider_home: 120

notify:
  name: sockerbot
  platform: telegram
  api_key: !secret telegram_api
  chat_id: !secret chat_id

 
 
#######################
####### Sensors #######
#######################

sensor:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
      
  # - platform: plex
    # host: 192.168.1.80
    # username: !secret plex_user
    # password: !secret plex_pass
    # server: Flashlight

sensor 2:    
  platform: forecast
  api_key: !secret forecast_api
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary
    - wind_speed
    - wind_bearing
    - precip_type

  # - platform: google_travel_time
    # name: Home to Work
    # api_key: !secret google_api
    # origin: !secret travel_origin
    # destination: !secret travel_destination
    # options:
      # arrival_time: 08:00:00
      # mode: transit

  # - platform: sabnzbd
    # name: SAB
    # api_key: !secret sab_api
    # base_url: !secret sab_url
    # monitored_variables:
      # - 'current_status'
      # - 'queue_size'
      
#####################    
####### Zones #######
#####################

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  radius: 100
  icon: mdi:home-variant

zone 2:
  name: Work
  latitude: !secret lat_work
  longitude: !secret long_work
  radius: 300
  icon: mdi:home-modern

zone 3:
  name: WhoValley
  latitude: !secret lat_who
  longitude: !secret long_who
  radius: 100
  icon: mdi:gondola
  passive: true

######################
####### Scenes #######
######################

scene:
  - name: 'Normal Mode'
    entities:
      light.vardagsrum_tak_1:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
      light.vardagsrum_tak_2:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
      light.vardagsrum_tak_3:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
      light.vardagsrum_tak_4:
        state: on
        brightness: 49
        color_temp: 424
        rgb_color: [152,110,51]
        
  - name: 'Kitchen On'
    entities:
      light.kk:
        state: on
        brightness: 254
        color_temp: 199
        rgb_color: [255,240,219]
        
  - name: 'Night Lights'
    entities:
      light.vardagsrum_tak_1:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]
      light.vardagsrum_tak_2:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]
      light.vardagsrum_tak_3:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]
      light.vardagsrum_tak_4:
        state: on
        brightness: 12
        color_temp: 500
        rgb_color: [51,51,205]  
      light.kk:
        state: on
        brightness: 75
        color_temp: 500
        rgb_color: [51,51,205]

  - name: 'Sunset'
    entities:
      light.vardagsrum_tak_1:
        state: on
        brightness: 248
        color_temp: 385
        rgb_color: [255,213,66]
      light.vardagsrum_tak_2:
        state: on
        brightness: 230
        color_temp: 500
        rgb_color: [255,96,0]
      light.vardagsrum_tak_3:
        state: on
        brightness: 248
        color_temp: 385
        rgb_color: [255,213,66]
      light.vardagsrum_tak_4:
        state: on
        brightness: 248
        color_temp: 500
        rgb_color: [255,170,48]  
      light.kk:
        state: on
        brightness: 249
        color_temp: 500
        rgb_color: [255,170,45]
        
  - name: 'All Off'
    entities:
      light.vardagsrum_tak_1:
        state: off
      light.vardagsrum_tak_2:
        state: off
      light.vardagsrum_tak_3:
        state: off
      light.vardagsrum_tak_4:
        state: off
      light.kk:
        state: off
      light.sovrum:
        state: off


#############################
####### Input Boolean #######
#############################      

input_boolean:
  home_away:
    name: Disable Home / Away Mode
    initial: off
    icon: mdi:map-marker-off       

##########################
####### Automation #######
##########################

automation:
- alias: 'Coming Home'
  trigger:
    - platform: state
      entity_id: group.dwellers
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: time
        before: '22:30'
      - condition: state
        entity_id: input_boolean.home_away
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.sunset
    - service: notify.sockerbot
      data:
        message: Welcome home! Truning lights on!

- alias: 'Coming Home Late'
  trigger:
    - platform: state
      entity_id: group.dwellers
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '22:30'
        before: '02:59'
      - condition: state
        entity_id: input_boolean.home_away
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.night_lights
    - service: notify.sockerbot
      data:
        message: Welcome home. Late night out?

- alias: 'Away Mode'
  trigger:
    platform: state
    entity_id: group.dwellers
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.home_away
      state: 'off'
  action:
    - service: light.turn_off
      entity_id:
      - group.ceiling
      - group.lights
    - service: notify.sockerbot
      data:
        message: Good bye. Have a nice time!
        

######################
####### Groups #######
######################

group:

  default_view:
    view: yes
    entities:
      - group.dwellers
      - group.transit
      - group.info
      - group.weather
      
  lightsview:
    name: Lights
    view: yes
    icon: mdi:lightbulb
    entities:
      - group.ceiling
      - group.lights

  lightsmodes:
    name: Lights modes
    view: yes
    icon: mdi:spotlight-beam
    entities:
      - group.modes

      
  media:
    name: Media
    view: yes
    icon: mdi:youtube-play
    entities:
      - media_player.kurvan
      - media_player.my_qv151e
      - media_player.plex_web_chrome
      - media_player.ponyo
      
  automation:
    name: Automation
    view: yes
    icon: mdi:settings
    entities:
      - group.automation_override

  Automation Override:
   - input_boolean.home_away   
   
  dwellers:
    name: Dwellers
    entities:
    - device_tracker.c0eefb4a7df9

#  transit:
#    name: Transit
#    entities:
#    - sensor.home_to_work
   
  info:
    name: Info
    entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.plex
    - sensor.sab_status
    - sensor.sab_queue

  weather:
    name: Weather
    entities:
    - sun.sun
    - sensor.weather_summary
    - sensor.weather_temperature
    - sensor.weather_precip_type
    - sensor.weather_wind_speed
    - sensor.weather_wind_bearing
    - sensor.weather_hourly_summary
 
  modes:
    name: Light modes
    entities:
    - scene.normal_mode
    - scene.kitchen_on
    - scene.sunset
    - scene.night_lights
    - scene.all_off

  ceiling:
    name: Ceiling
    entities:
    - light.vardagsrum_tak_1
    - light.vardagsrum_tak_2
    - light.vardagsrum_tak_3
    - light.vardagsrum_tak_4
   
  lights:
    name: Other lights
    entities:
    - light.sovrum
    - light.kk
    
