homeassistant:
  name: Sockr Base
  latitude: !secret lat
  longitude: !secret long
  elevation: 26
  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

http:
#  api_password: !secret http_password
  

##########################
####### Components #######
##########################

updater:
history:
logbook:
frontend:
discovery:
sun:
recorder:
  purge_days: 7

logger:
    default: info
    logs:
     group.settings: critical

light:
  - platform: hue
    host: 192.168.2.40
    allow_unreachable: true    
  - platform: lifx
    brodcast: 192.168.2.255
  
media_player:
  - platform: cast
    host: 192.168.2.27
  - platform: plex

device_tracker:
#  platform: nmap_tracker
#  hosts: 192.168.2.15-45
#  home_interval: 5
#  track_new_devices: no
#  interval_seconds: 30
#  consider_home: 70
  - platform: unifi
    username: !secret unifi_user
    password: !secret unifi_pass
    track_new_devices: no
    interval_seconds: 10


notify:
  name: sockerbot
  platform: telegram
  api_key: !secret telegram_api
  chat_id: !secret chat_id

 
 
#######################
####### Sensors #######
#######################

sensor:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 4
    - 8
    - 12
    - 16
    - 20
  monitored_conditions:
    - ping
    - download
    - upload
    
sensor 2:
  platform: plex
  host: 192.168.1.80
  username: !secret plex_user
  password: !secret plex_pass
  server: Flashlight

sensor 3:    
  platform: darksky
  api_key: !secret forecast_api
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary
    - wind_speed
    - wind_bearing
    - precip_type

sensor 4:
  platform: google_travel_time
  name: Home to Work
  api_key: !secret google_api
  origin: !secret travel_origin
  destination: !secret travel_destination
  options:
    arrival_time: 08:00:00
    mode: transit

sensor 5:
  platform: sabnzbd
  name: SAB
  api_key: !secret sab_api
  host: !secret sab_url
  port: 8080
  monitored_variables:
    - 'current_status'
    - 'queue_size'
      
#####################    
####### Zones #######
#####################

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  radius: 100
  icon: mdi:home-variant

zone 2:
  name: Work
  latitude: !secret lat_work
  longitude: !secret long_work
  radius: 300
  icon: mdi:home-modern

zone 3:
  name: WhoValley
  latitude: !secret lat_who
  longitude: !secret long_who
  radius: 100
  icon: mdi:gondola
  passive: true

#############################
####### Input Boolean #######
#############################      

input_boolean:
  home_away:
    name: Disable Home / Away Mode
    initial: off
    icon: mdi:map-marker-off    

  alarm:
    name: Weekday Alarm
    initial: on
    icon: mdi:alarm-check
    
##########################
######## Includes ########
##########################

automation: !include automation.yaml


######################
####### Scenes #######
######################

scene: !include scene.yaml


        
######################
####### Groups #######
######################

group: !include groups.yaml 
