
sensor:
# Weather Prediction
- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity

# Plex Monitor

- platform: plex
  name: Plex Spy
  host: 192.168.2.80
  port: 29301
  server: Flashlight

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload